name: update ppmy rss

on:
  schedule:
    - cron: '0 2 * * *'  # 每天 10:00（北京时间）执行
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: pip install -r requirements.txt

      - name: 运行爬虫
        run: python crawler.py

      - name: 提交并推送更新
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "ppmy-rss-bot"
          author_email: "41898282+github-actions[bot]@users.noreply.github.com"
          message: "自动更新 RSS: $(date -u +'%Y-%m-%d %H:%M:%S') UTC"
