name: update ppmy rss

on:
  schedule:
    - cron: '0 * * * *'  # 每天 10:00（北京时间）执行
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (浅克隆加速)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 缓存 pip 依赖
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: 安装依赖（仅首次执行慢）
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 运行爬虫
        run: python crawler.py

      - name: Commit generated RSS
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "ppmy-rss-bot"
          author_email: "41898282+github-actions[bot]@users.noreply.github.com"
          message: "自动更新 RSS: $(date -u +'%Y-%m-%d %H:%M:%S') UTC"
          add: "docs/ppmy_rss.xml"
